# Generated by Django 4.2.3 on 2023-07-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adopt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="pics/%Y/%m/%d"),
        ),
    ]
