# Generated by Django 4.2.2 on 2023-07-03 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adopt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="adotante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adopted_pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="donatario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donated_pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
