# Generated by Django 4.2.8 on 2023-12-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adopt", "0003_remove_pet_foto_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="adopt.pet",
            ),
        ),
    ]
