# Generated by Django 4.2.8 on 2023-12-19 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adopt", "0004_alter_picture_pet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="peso",
        ),
    ]
