# Generated by Django 4.2.8 on 2023-12-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adopt", "0005_remove_pet_peso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="altura",
            field=models.IntegerField(),
        ),
    ]
