# Generated by Django 4.2.2 on 2023-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adopt", "0002_alter_pet_adotante_alter_pet_donatario"),
        ("authentication", "0004_alter_profile_favorite_pets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="favorite_pets",
            field=models.ManyToManyField(blank=True, to="adopt.pet"),
        ),
    ]
